# Generated by Django 4.2.3 on 2023-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
